Canary fix
aws-cloudformation/aws-cloudformation-resource-providers-transitgateway pull request #95
Opened 2022-01-04 17:15 UTC by suhaniladani

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-31 14:36 UTC, sandeepbellary18 approved these changes

2022-01-31 20:36 UTC, sandeepbellary18 approved these changes

2022-02-01 14:52 UTC, wuiidl requested changes
Looks good, please remove the one `//System.out.println` then we are good to go.

2022-02-01 14:52 UTC, wuiidl commented on aws-ec2-transitgatewayvpcattachment/src/main/java/com/aws/ec2/transitgatewayvpcattachment/workflow/read/Read.java
> +        //System.out.println("this"+response.subnetIds());
please remove this comment

2022-02-02 16:11 UTC, merged